feat: Custom z bin search order
acts-project/acts pull request #1169
Opened 2022-02-17 11:51 UTC by LuisFelipeCoelho

This PR introduces a custom z looping feature, 
which allows us to change the order in which `BinnedSPGroup` search for the Space Points.

In the Main branch the groups are sorted in **phi** and **z** in ascending order. But in Athena **z** follows the order within the vector `{1, 2, 3, 4, 11, 10, 9, 8, 6, 5, 7}`

This PR introduces this same custom looping approach with the vector `zBinsCustomLooping`. If it is not defined, the previous behaviour is preserved.

@noemina @paulgessinger @robertlangenberg

2022-03-22 15:48 UTC, robertlangenberg commented on Core/include/Acts/Seeding/BinnedSPGroup.hpp
> +    topBinIndices = m_topBinFinder->findBins(phiIndex, this_zIndex, grid);
please add a short comment explaining what happens

2022-03-22 15:51 UTC, robertlangenberg requested changes
just add a few comments to make the code easier to understand and I'm happy :)

2022-03-22 15:52 UTC, robertlangenberg commented on Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp
> +
please add comment what consistent/inconsistent means

2022-03-22 16:31 UTC, LuisFelipeCoelho commented on Core/include/Acts/Seeding/BinnedSPGroup.hpp
> +    topBinIndices = m_topBinFinder->findBins(phiIndex, this_zIndex, grid);
ok! I will add some comments

2022-03-28 08:36 UTC, LuisFelipeCoelho commented on Examples/Algorithms/TrackFinding/src/SeedingAlgorithm.cpp
> +
I added some comments, please let me know if they are enough

2022-03-29 11:01 UTC, robertlangenberg approved these changes

2022-03-30 14:31 UTC, merged