doc: adding acts project page
acts-project/acts pull request #1392
Opened 2022-08-08 11:39 UTC by asalzburger

This PR adds a high level "ACTS Project" documentation page with some basic information and pointers.

2022-08-08 12:47 UTC, benjaminhuth commented on docs/acts_project.md
> +Code spill-over fromt he R&D lines into the main Acts repository are performed on demand and depending on the maturity of the R&D projects.
```suggestion
Code spill-over from he R&D lines into the main Acts repository are performed on demand and depending on the maturity of the R&D projects.
```

2022-08-10 05:22 UTC, AJPfleger requested changes

2022-08-10 05:22 UTC, AJPfleger commented on docs/acts_project.md
> +Acts is designed as a library that *contains components* for assembling a track reconstruction suite for High Energy Physics and Nuclear Physics. Acts does not strive to provide a complete experiment
```suggestion
Acts is designed as a library that *contains components* for assembling a track reconstruction suite for High Energy Physics and Nuclear Physics. Acts does not strive to provide a complete experiment framework, but rather modules and connections to be used within an experiment context. These connections contain e.g. binding mechanisms to different geometry libraries, a cost-free yet flexible mechanism to use experiment specific contextual data (calibrations, detector alignment, experiment conditions), or simply the possibility to integrate an external screen logging facility.
```

2022-08-10 05:22 UTC, AJPfleger commented on docs/acts_project.md
> +```{tip} Developers and R&D meetings can be found in the [Acts indico category](https://indico.cern.ch/category/7968/).
```suggestion
```{tip}
Developers and R&D meetings can be found in the [Acts indico category](https://indico.cern.ch/category/7968/).
```

2022-08-10 05:22 UTC, AJPfleger commented on docs/acts_project.md
> + In order to minimize virtual function calls and complex inheritence schemes, Acts does - in general - not define module interfaces, but rather relies on a data centric pattern. Whereever possible, c
```suggestion
 In order to minimize virtual function calls and complex inheritance schemes, Acts does - in general - not define module interfaces, but rather relies on a data-centric pattern. Wherever possible, composition is favoured over inheritance/code extension.
```

2022-08-10 05:22 UTC, AJPfleger commented on docs/acts_project.md
> +In addition, two dedicated R&D lines are part of the `acts-project`, one for machine learning based/inspired modules [acts-machine-learning](mailto:acts-machine-learning@cern.ch), and one for massive
```suggestion
In addition, two dedicated R&D lines are part of the `acts-project`, one for machine learning based/inspired modules [acts-machine-learning](mailto:acts-machine-learning@cern.ch), and one for massively parallel code execution [acts-parallelization](mailto:acts-parallelization@cern.ch), which mainly focuses on GPU accelerators and portability.
```

2022-08-10 05:22 UTC, AJPfleger commented on docs/acts_project.md
> + Acts should also provide a testbed for fruitfull algorithm R&D, and hence is closely coupled to the development of the [Open Data Detector](https://gitlab.cern.ch/acts/OpenDataDetector) which can be
```suggestion
 Acts should also provide a testbed for fruitful algorithm R&D, and hence is closely coupled to the development of the [Open Data Detector](https://gitlab.cern.ch/acts/OpenDataDetector) which can be built as a `thirdparty` dependency as part of the Acts project, and builds the backbone of the chain demonstrators.
```

2022-08-10 05:22 UTC, AJPfleger commented on docs/acts_project.md
> + * The `Fatras` library contains a fast track simulation module, that is based on the same concepts that are used for the [ATLAS Fatras](https://cds.cern.ch/record/1091969?ln=de) fast track simulatio
```suggestion
 * The `Fatras` library contains a fast track simulation module, that is based on the same concepts that are used for the [ATLAS Fatras](https://cds.cern.ch/record/1091969) fast track simulation  
```

2022-08-10 05:22 UTC, AJPfleger commented on docs/acts_project.md
> +
```suggestion
```

2022-08-10 05:23 UTC, AJPfleger commented on docs/acts_project.md
> +Code spill-over fromt he R&D lines into the main Acts repository are performed on demand and depending on the maturity of the R&D projects.
```suggestion
Code spill-over from the R&D lines into the main Acts repository are performed on demand and depending on the maturity of the R&D projects.
```

2022-08-10 08:10 UTC, AJPfleger approved these changes

2022-08-10 16:59 UTC, merged