docs: Exa.TrkX
acts-project/acts pull request #1517
Opened 2022-09-14 07:39 UTC by benjaminhuth

Depends on #1473

2022-09-15 12:21 UTC, tboldagh requested changes

2022-09-15 12:21 UTC, tboldagh commented on docs/plugins/exatrkx.md
> +- The **ONNX** backend is currently not as well maintained as the TorchScript backend. The main reason is, that there are scatterin operators missing in ONNX, so that the graph neural network cannot
"The implementation also uses *cugraph* for graph building instead of *Boost.Graph*." That is also said later in Graph building paragraph.

2022-09-15 12:21 UTC, tboldagh commented on docs/plugins/exatrkx.md
> +All implementations should inherit from {class}`Acts::ExaTrkXTrackFindingBase`, so that they can be passed via a `std::shared_ptr` to the {class}`ActsExamples::TrackFindingAlgorithmExaTrkX`. The algo
"should"  or just "inherits". The justification seems too technical. I would suggest to just write that this interface is used by that algorithm.

2022-09-15 12:21 UTC, tboldagh commented on docs/plugins/exatrkx.md
> +
By now the reader would not know what the algorithm operates on. I.e. space points and what are the output. I.e. track seeds. Maybe worth adding such basic info too.

2022-09-22 09:12 UTC, benjaminhuth commented
@tboldagh Thank you very much for your comments, I have addressed them now. Could you take a look and approve? Then we can get this in!

2022-10-03 07:51 UTC, paulgessinger approved these changes
Let's get this in.

2022-10-03 08:57 UTC, merged