Update run_formatting.md
acts-project/acts pull request #1667
Opened 2022-11-09 19:22 UTC by jahreda

Add explanation of how to download clang-format recommended changes from the CI job

PLEASE FOLLOW THE CHECKLIST BELOW WHEN CREATING A NEW PULL REQUEST. THE
CHECKLIST IS FOR YOUR INFORMATION AND MUST BE REMOVED BEFORE SUBMITTING THE PULL
REQUEST.

## Checklist

- [ ] Does the PR title follow the `<prefix>: title` scheme?

    The prefix must be one of:

    - `fix`: for a bugfix
    - `feat`: for a new feature
    - `refactor`: for an improvement of an existing feature
    - `perf`, `test`: for performance- or test-related changes
    - `docs`: for documentation-related changes
    - `build`, `ci`, `chore`: as appropriated for infrastructure changes

- [ ] Does this modify the public API as defined in `docs/versioning.rst`?

    - [ ] Does the PR title contain a `!` to indicate a breaking change?
    - [ ] Is there section starting with `BREAKING CHANGE:` in the PR body
        that explains the breaking change?

- [ ] Is the PR ready to be merged?

    - [ ] If not: is it marked as work-in-progress using the `WIP` label?

- [ ] Is the PR assigned to a milestone? This should be `next` unless you
    target a specific release.

- [ ] Does this PR close an existing issue?

    - [ ] Is the issue correctly linked so it will be automatically closed
        upon successful merge (See closing keywords link in the sidebar)?
    - [ ] Does the PR milestone match the issue milestone?

2022-11-10 07:45 UTC, AJPfleger requested changes
Hi, maybe you could adapt some things in this PR:
- More expressive title e.g. `docs: how to get clang-format changes from CI`
- Edit first comment (You still have the reminder text in it)

2022-11-10 07:45 UTC, AJPfleger commented on docs/contribution/run_formatting.md
> +portion of the CI job and scrolling down to the bottom of the page (see *Changed*).
```suggestion
portion of the CI job and scrolling down to the bottom of the page (see *Changed*).
However, it is suggested to run the `CI/check_format` locally before committing, to not
clog the shared resources with repeated checks.
```

2022-11-11 15:10 UTC, andiwand approved these changes

2022-11-11 15:12 UTC, AJPfleger approved these changes

2022-11-11 18:01 UTC, merged