feat: skip unnecessary iterations in seed filter if SPs are sorted by curvature
acts-project/acts pull request #1672
Opened 2022-11-11 13:58 UTC by LuisFelipeCoelho

2022-11-18 07:13 UTC, tboldagh requested changes
The change looks alright.
Just had few suggestions that could improve understanding the code by others.  
I would like to make a general comment. As of now the function has 200+ lines of quite involved logic. 
It may help to make it easier to follow if it could be partitioned in a few smaller functions with meaningful names.

2022-11-18 07:13 UTC, tboldagh commented on Core/include/Acts/Seeding/SeedFilter.ipp
> -  for (auto& i : idx) {
Just reading this code as is, it may be better to give variable `idx` a more verbose name: i.e. `topSpSize`
same for the `i`, maybe topSpIndex?

2022-11-18 07:13 UTC, tboldagh commented on Core/include/Acts/Seeding/SeedFilter.ipp
> +          startCompTopLoopIdx = j;
Another suggestion about the name. The `j` is good if the loop is small. For anything longer than 10 lines it is better us use some more meaningful name.

2022-11-18 07:13 UTC, tboldagh commented on Core/include/Acts/Seeding/SeedFilter.ipp
> +      float otherTop_r = m_cfg.useDeltaRorTopRadius
Variable naming comment, camelCase style is used in this code, so maybe `otherTopR` ?

2022-11-18 07:13 UTC, tboldagh commented on Core/include/Acts/Seeding/SeedFilter.ipp
> +  // loop over top SPs and other compatible top SP candidates
Is there an important assumption about the SPs being sorted by phi used here? May be worth mentioning in the comment.

2022-11-18 13:57 UTC, LuisFelipeCoelho commented
I tested this with 500 ttbar events with PU=200 in standalone and it seems to be slightly faster FYI: @paulgessinger 
![ITkSeeding_ttbar_mu200_PPPtime](https://user-images.githubusercontent.com/56648068/202721261-3318732f-ab50-48d5-88b9-3f994b6c1f2d.png)

2022-11-22 09:26 UTC, tboldagh approved these changes
These changes look good to me.

2022-11-22 11:45 UTC, merged