feat: Visualization for DetectorVolume and Portal
acts-project/acts pull request #1762
Opened 2022-12-19 15:37 UTC by Matthewharri

This PR adds in visualization for DetectorVolume and Portals. This uses the existing method of `drawSurface` for the visualization. When drawing, the portals are drawn such that if the Portal contains two links it is drawn as green (as Portals should have two links), otherwise will be drawn red, indicating a link is missing.

2022-12-21 08:04 UTC, asalzburger requested changes
Looks all good, I would suggest one change though:
- the `drawX(...)` should get through the signature the `ViewConfig connected`, `ViewConfig unconnected` with the green/red as two default options.

2023-01-06 15:26 UTC, Matthewharri commented
@asalzburger this should be all set now with the change you suggested.

2023-01-16 09:26 UTC, paulgessinger approved these changes

2023-01-16 09:28 UTC, paulgessinger commented on Core/include/Acts/Visualization/GeometryView3D.hpp
> +      const ViewConfig& unconnected = ViewConfig({255, 0, 0}));
Fo be consistent with the `cpp` and make clang-tidy happy:

```suggestion
  /// @param disconnected The config for unconnected portals
  static void drawDetectorVolume(
      IVisualization3D& helper,
      const Acts::Experimental::DetectorVolume& volume,
      const GeometryContext& gctx,
      const Transform3& transform = Transform3::Identity(),
      const ViewConfig& connected = ViewConfig({0, 255, 0}),
      const ViewConfig& disconnected = ViewConfig({255, 0, 0}));
```

2023-01-17 08:43 UTC, paulgessinger commented
@Matthewharri sorry I've missed that the parameter name mismatch is also there in the other files.

2023-01-17 08:51 UTC, benjaminhuth approved these changes

2023-01-17 16:31 UTC, paulgessinger commented
Wow, I managed to mess that up 😅. I pushed another commit, hopefully that's it.

2023-01-18 09:20 UTC, benjaminhuth approved these changes

2023-01-18 12:28 UTC, merged