refactor: Make surface intersection tolerance configurable
acts-project/acts pull request #2106
Opened 2023-05-06 18:38 UTC by andiwand

`s_onSurfaceTolerance` is used in a bunch of places where the user might actually expect a configurable tolerance.

in this PR I add a tolerance parameter to `Surface::intersect` which can then be used by the navigator or target reached aborter

2023-05-07 08:11 UTC, asalzburger commented
I like that! Doesn't that actually qualify as a breaking change?

Will do the review later on that.

2023-05-07 17:29 UTC, andiwand commented
> I like that! Doesn't that actually qualify as a breaking change?

good point - I am not sure. if we are expecting the users to have their own surfaces, yes. if the only use the interface of the surface then the api should be stable because of the default value

2023-05-11 10:16 UTC, asalzburger requested changes
Can you change the `double` to `ActsScalar` please ?

2023-05-11 12:20 UTC, andiwand commented on Core/include/Acts/Surfaces/CylinderSurface.hpp
> +      double tolerance = s_onSurfaceTolerance) const final;
```suggestion
      ActsScalar tolerance = s_onSurfaceTolerance) const final;
```

2023-05-11 12:20 UTC, andiwand commented on Core/include/Acts/Surfaces/DiscSurface.hpp
> +      double tolerance = s_onSurfaceTolerance) const final;
```suggestion
      ActsScalar tolerance = s_onSurfaceTolerance) const final;
```

2023-05-11 12:20 UTC, andiwand commented on Core/include/Acts/Surfaces/LineSurface.hpp
> +      double tolerance = s_onSurfaceTolerance) const final;
```suggestion
      ActsScalar tolerance = s_onSurfaceTolerance) const final;
```

2023-05-11 12:20 UTC, andiwand commented on Core/include/Acts/Surfaces/PlaneSurface.hpp
> +      double tolerance = s_onSurfaceTolerance) const final;
```suggestion
      ActsScalar tolerance = s_onSurfaceTolerance) const final;
```

2023-05-11 12:20 UTC, andiwand commented on Core/include/Acts/Surfaces/Surface.hpp
> +      double tolerance = s_onSurfaceTolerance) const = 0;
```suggestion
      ActsScalar tolerance = s_onSurfaceTolerance) const = 0;
```

2023-05-11 12:20 UTC, andiwand commented on Core/include/Acts/Surfaces/detail/PlanarHelper.hpp
> +                                const Vector3& direction, double tolerance) {
```suggestion
                                const Vector3& direction, ActsScalar tolerance) {
```

2023-05-11 12:21 UTC, andiwand commented on Core/src/Surfaces/ConeSurface.cpp
> +    double tolerance) const {
```suggestion
    ActsScalar tolerance) const {
```

2023-05-11 12:21 UTC, andiwand commented on Core/src/Surfaces/CylinderSurface.cpp
> +    double tolerance) const {
```suggestion
    ActsScalar tolerance) const {
```

2023-05-11 12:21 UTC, andiwand commented on Core/src/Surfaces/DiscSurface.cpp
> +    double tolerance) const {
```suggestion
    ActsScalar tolerance) const {
```

2023-05-11 12:21 UTC, andiwand commented on Core/src/Surfaces/LineSurface.cpp
> +    double tolerance) const {
```suggestion
    ActsScalar tolerance) const {
```

2023-05-11 12:22 UTC, andiwand commented on Core/src/Surfaces/PlaneSurface.cpp
> +    double tolerance) const {
```suggestion
    ActsScalar tolerance) const {
```

2023-05-11 12:22 UTC, andiwand commented on Tests/UnitTests/Core/Propagator/NavigatorTests.cpp
> +    double targetTolerance = s_onSurfaceTolerance;
```suggestion
    ActsScalar targetTolerance = s_onSurfaceTolerance;
```

2023-05-11 12:22 UTC, andiwand commented on Tests/UnitTests/Core/Surfaces/SurfaceStub.hpp
> +                                const double /*tolerance*/) const final {
```suggestion
                                const ActsScalar /*tolerance*/) const final {
```

2023-05-14 13:30 UTC, merged