ci: Add codespell to CI
acts-project/acts pull request #2218
Opened 2023-06-19 09:07 UTC by benjaminhuth

This adds a spell checking tool to the CI along with a lot of fixes.

2023-06-19 13:50 UTC, andiwand approved these changes
looks good to me. maybe @paulgessinger wants to take a look before we merge

2023-06-19 14:58 UTC, paulgessinger commented
Could be a good idea. Did you check this for false hits?

2023-06-19 14:58 UTC, paulgessinger commented
Also: could we get the FPE PR in before this one?

2023-06-19 15:36 UTC, andiwand approved these changes

2023-06-19 16:02 UTC, AJPfleger requested changes
I added `dThe` to the ignore list.

Do we need to mark this PR as breaking since `auxiliary` may be part of the python API?

2023-06-19 16:02 UTC, AJPfleger commented on CI/codespell_ignore.txt
> +ans
```suggestion
ans
dthe
```
should we also sort them alphabetically?

2023-06-19 20:12 UTC, benjaminhuth commented on CI/check_spelling
> +    echo "codespell detected incorrect spelling. You have to options how to deal with this:"
Haha kind of sad to have such an error in a spelling-PR :D

2023-06-20 07:41 UTC, benjaminhuth commented
> Do we need to mark this PR as breaking since `auxiliary` may be part of the python API?

The python API is not subject of our versioning I think.

2023-06-20 11:42 UTC, andiwand approved these changes

2023-06-20 14:46 UTC, merged