feat: Implementation of a point surface
acts-project/acts pull request #2297
Opened 2023-07-11 12:27 UTC by andiwand

WIPWIP

2023-07-14 08:33 UTC, asalzburger requested changes
Can you add a UnitTest for this ?

2023-07-14 08:33 UTC, asalzburger commented on Core/include/Acts/Surfaces/PointBounds.hpp
> +  enum BoundValues : int { eR = 0, eSize = 2 };
I don't understand eSize ==2 here? Shouldn't that be `eSize==1` ?

2023-07-14 08:33 UTC, asalzburger commented on Core/include/Acts/Surfaces/PointSurface.hpp
> +/// @note It leaves the type() method virtual, so it can not be instantiated
Is this a leftover comment from the LineSurface?

2023-07-14 08:33 UTC, asalzburger commented on Core/include/Acts/Surfaces/PointBounds.hpp
> +///
Can you add what the local position for a `PointSurface` means?

2023-07-14 08:35 UTC, andiwand commented
> Can you add a UnitTest for this ?

sure! this is actually just a copy paste and some small adoptions from the `LineSurface` right now. will continue working on this when there is more time

2023-09-06 10:20 UTC, andiwand commented
closing for now as I do not have time to work on that

2023-09-06 10:20 UTC, closed without merging