feat: Configurable and more flexible binning for CKFPerformanceWriter
acts-project/acts pull request #2379
Opened 2023-08-17 12:59 UTC by benjaminhuth

This allows for a more flexible binning for the `PlotTools`, and exposes this to python. For example, a binning can be configured like this:

```python
binningCfg = {
    "Pt" : acts.examples.Binning("pT", list(np.logspace(-2,2,40))),
    "Eta" : acts.examples.Binning("eta", 40, -4, 4),
    "Phi" : acts.examples.Binning("phi", 100, -3.15, 3.15),
}

s.addWriter(
    acts.examples.CKFPerformanceWriter(
		...
        effPlotToolConfig = acts.examples.EffPlotToolConfig(self.binningCfg),
    )
)
```

2023-08-17 13:02 UTC, benjaminhuth commented on Examples/Framework/include/ActsExamples/Utilities/Helpers.hpp
>    Binning() = default;
```suggestion
  Binning() : m_bins({0.0}) {}
```

2023-08-17 13:05 UTC, andiwand submitted a review, later dismissed
nice!

2023-08-17 13:06 UTC, andiwand approved these changes

2023-08-17 13:13 UTC, andiwand submitted a review, later dismissed

2023-08-17 13:54 UTC, paulgessinger commented
This has physmon failures.

2023-08-29 08:55 UTC, AJPfleger requested changes

2023-08-29 08:55 UTC, AJPfleger commented on Examples/Python/src/Output.cpp
> +// Copyright (C) 2023 CERN for the benefit of the Acts project
```suggestion
// Copyright (C) 2021-2023 CERN for the benefit of the Acts project
```

2023-08-29 08:55 UTC, AJPfleger commented on Examples/Framework/src/Validation/ResPlotTool.cpp
> +// Copyright (C) 2023 CERN for the benefit of the Acts project
```suggestion
// Copyright (C) 2019-2023 CERN for the benefit of the Acts project
```

2023-08-29 08:55 UTC, AJPfleger commented on Examples/Framework/src/Utilities/Helpers.cpp
> +// Copyright (C) 2023 CERN for the benefit of the Acts project
```suggestion
// Copyright (C) 2019-2023 CERN for the benefit of the Acts project
```

2023-08-29 08:55 UTC, AJPfleger commented on Examples/Framework/include/ActsExamples/Utilities/Helpers.hpp
> +// Copyright (C) 2023 CERN for the benefit of the Acts project
```suggestion
// Copyright (C) 2019-2023 CERN for the benefit of the Acts project
```

2023-08-29 18:06 UTC, merged

2023-08-29 18:55 UTC, acts-project-service commented
## :white_check_mark: Athena integration test results
### :white_check_mark: All tests successful

|status|job|
|------|---|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078160) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078159) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078158) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078157) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078156) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078155) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078154) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078153) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078152) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078151) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078150) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078149) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078148) |
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078147) |
|:green_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078146) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078145) |
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32078144) |