feat: extract impact parameter covariance matrix
acts-project/acts pull request #2464
Opened 2023-09-19 15:44 UTC by felix-russo

Allow extraction of the impact parameter covariance matrix (i.e., the entries involving d0, z0, and, optionally, t)

2023-09-25 08:19 UTC, paulgessinger requested changes
I like the idea! I have some comments.
Mainly it's choices, but I think you're returning an invalid dangling referene, which is unsafe.

2023-09-25 08:19 UTC, paulgessinger commented on Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
> +    if (nDim != 2 and nDim != 3) {
This can be a static_assert, since `nDim` is known at compile-time.

2023-09-25 08:19 UTC, paulgessinger commented on Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
> +    if (nDim == 3) {
```suggestion
    if constexpr (nDim == 3) {
```

2023-09-25 08:19 UTC, paulgessinger commented on Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
> +  const ActsVector<nDim>& impactParameters() const {
This returns a reference to a local stack variable, so will dangle immediately.
You could return a map type, that points to the underlying `m_params` member variable, which would be safer.

Also: I'm wondering if separate names, like `impactParameters2()` and `impactParameters3()` would make clearer what's being accessed here.

2023-09-25 08:19 UTC, paulgessinger commented on Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
> +    if (nDim != 2 and nDim != 3) {
`static_assert`

2023-09-25 08:19 UTC, paulgessinger commented on Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
> +    if (nDim == 3) {
```suggestion
    if constexpr (nDim == 3) {
```

2023-09-25 08:19 UTC, paulgessinger commented on Core/include/Acts/EventData/GenericBoundTrackParameters.hpp
> +  std::optional<ActsSquareMatrix<nDim>> impactParameterCovariance() const {
Same potential consideration concerning the name vs template parameter.

2023-09-25 08:19 UTC, paulgessinger commented on Core/include/Acts/Vertexing/AdaptiveGridTrackDensity.ipp
> +  SquareMatrix2 cov = trk.impactParameterCovariance().value();
Here, the default of `2` and hence $d_0, z_0$ would not be obvious to me, for example.

2023-09-26 11:55 UTC, paulgessinger approved these changes

2023-09-26 13:16 UTC, merged

2023-09-26 13:48 UTC, acts-project-service commented
## :red_circle: Athena integration test results
### :red_circle: Some tests have failed!
Please investigate the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6251320)!

|status|job|
|------|---|
|:green_circle: | [run_unit_tests](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731977) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsWorkflow.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731976) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateTracks.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731975) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsCoreSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731974) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateActsSpacePoints.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731973) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731972) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateOrthogonalSeeds.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731971) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsValidateClusters.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731970) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsPersistifyEDM.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731969) |
|:green_circle: | [run_ci_tests: ../athena/AtlasTest/CITest/test/ActsKfRefitting.sh](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731968) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsExtrapolationAlgTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731967) |
|:green_circle: | [run_ci_tests: python3 ../athena/Tracking/Acts/ActsGeometry/test/ActsITkTest.py](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731966) |
|:green_circle: | [run_workflow_tests_run4_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731965) |
|:green_circle: | [run_workflow_tests_run2_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731964) |
|:red_circle: | [run_workflow_tests_run2_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731963) |
|:green_circle: | [run_workflow_tests_run3_mc](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731962) |
|:green_circle: | [run_workflow_tests_run3_data](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/32731961) |