feat!: volume agnostic material mapping
acts-project/acts pull request #2473
Opened 2023-09-21 20:39 UTC by asalzburger

This PR changes the material mapping quite dramatically. While the algorithmic code rests identical, the `SurfaceMaterialMapper` and `VolumeMaterialMapper` have now entirely separate functionality:
  * the surface mapper does only surface mapping and already implements `TrackingGeometry` and `Detector` schema
  * the volume mapper does only volume mapping (currently not yet fully supporting the `Detector` schema)

The Mappers are now designed to run in a chained setup, i.e. one mapper runs and returns a pair of `mapped` and `unmapped` tracks, the `unmapped` part is then processed by the subsequent mapper.

By doing so, the Mappers became `const correct` (except for the finalizeMaps) call, as modification of the input collection is not allowed anymore. 

This should allow the material mapping to be run in multithreaded mode, if the manipulation step of the state is `mutex` protected (to be proven yet).

2023-09-30 05:21 UTC, asalzburger commented
The example failures are in the material mapping, so probably not a fluke - I will check this early next week.

2023-11-09 15:40 UTC, AJPfleger requested changes

2023-11-09 15:40 UTC, AJPfleger commented on Tests/UnitTests/Core/Material/SurfaceMaterialMapperTests.cpp
> +  BOOST_CHECK(unmapped.second.materialInteractions.size() == 0u);
```suggestion
  BOOST_REQUIRE(surfaceState != nullptr);
  BOOST_CHECK_EQUAL(surfaceState->accumulatedMaterial.size(), 6u);

  // Run the mapping
  auto mTrack = createRecordedMaterialTrack(materialSteps);
  auto [mapped, unmapped] = smMapper.mapMaterialTrack(*surfaceState, mTrack);
  // Check that all material is mapped
  BOOST_CHECK_EQUAL(mapped.second.materialInteractions.size(),
              mTrack.second.materialInteractions.size());
  BOOST_CHECK_EQUAL(unmapped.second.materialInteractions.size(), 0u);
```

2023-11-09 15:40 UTC, AJPfleger commented on Tests/UnitTests/Core/Material/SurfaceMaterialMapperTests.cpp
> +              reunmapped.second.materialInteractions.size());
```suggestion
  BOOST_CHECK_EQUAL(mapped.second.materialInteractions.size(),
              remapped.second.materialInteractions.size());
  CHECK_CLOSE_ABS(mapped.second.materialInX0, remapped.second.materialInX0,
                  1e-10);
  CHECK_CLOSE_ABS(mapped.second.materialInL0, remapped.second.materialInL0,
                  1e-10);
  BOOST_CHECK_EQUAL(unmapped.second.materialInteractions.size(),
              reunmapped.second.materialInteractions.size());
```

2023-11-09 15:40 UTC, AJPfleger commented on Tests/UnitTests/Core/Material/SurfaceMaterialMapperTests.cpp
> +              mTrack.second.materialInteractions.size() - negativeSide);
```suggestion
  BOOST_CHECK_EQUAL(mapped.second.materialInteractions.size(), negativeSide);
  BOOST_CHECK_EQUAL(unmapped.second.materialInteractions.size(),
              mTrack.second.materialInteractions.size() - negativeSide);
```

2023-11-09 15:40 UTC, AJPfleger commented on Tests/UnitTests/Core/Material/SurfaceMaterialMapperTests.cpp
> +              mTrack.second.materialInteractions.size());
```suggestion
  BOOST_CHECK_EQUAL(mapped.second.materialInteractions.size(),
              mTrack.second.materialInteractions.size());
```

2023-11-09 15:40 UTC, AJPfleger commented on Tests/UnitTests/Core/Material/SurfaceMaterialMapperTests.cpp
> +              mTrack.second.materialInteractions.size() - negativeSide);
```suggestion
  BOOST_CHECK_EQUAL(remapped.second.materialInteractions.size(), negativeSide);
  BOOST_CHECK_EQUAL(reunmapped.second.materialInteractions.size(),
              mTrack.second.materialInteractions.size() - negativeSide);
```

2024-04-09 15:29 UTC, closed without merging