fix: and refactor geometric digitization
acts-project/acts pull request #2630
Opened 2023-11-04 12:53 UTC by benjaminhuth

* fix: activation was only 2D path, but must be 3D path. Otherwise, an upright track would get 0 activation...
* refactor: rename `Channelizer` to `Segmentizer`, add `Channelizer` that ties together the things

2023-11-09 15:11 UTC, asalzburger commented
Unit test is failing - is that expected ? Do we need to update the test?

2023-11-09 15:12 UTC, benjaminhuth commented
Hmm no is not expected. They *should* run through. I will check after the workshop

2023-11-09 15:53 UTC, AJPfleger commented
Could you also adapt the tests to what I did in #2632 ? :)

I didn't touch `Tests/UnitTests/Fatras/Digitization/ChannelizerTests.cpp` in my PR to avoid conflicts on your side.
Also the file `Tests/UnitTests/Fatras/Digitization/SegmentizerTests.cpp` will be new for me.

2023-11-10 08:14 UTC, asalzburger submitted a review, later dismissed
Makes sense, let's fix the UnitTests and get that in.

2023-11-10 08:14 UTC, asalzburger commented on Examples/Algorithms/Digitization/include/ActsExamples/Digitization/DigitizationAlgorithm.hpp
> +      const std::vector<ActsFatras::Segmentizer::ChannelSegment>& channels,
Makes sense! The naming is clearer.

2023-11-10 08:14 UTC, asalzburger commented on Examples/Algorithms/Digitization/src/DigitizationAlgorithm.cpp
> +              if (!channelsRes.ok() || channelsRes->empty()) {
I like the change to the Result object as well.

2023-11-10 08:14 UTC, asalzburger commented on Fatras/include/ActsFatras/Digitization/Channelizer.hpp
> +  /// and not pulling it from the surface->detectorElement directly?
Actually, we might want to remove the "thickness" from the detector element as it is a very planar detector oriented concept.

2023-11-10 08:14 UTC, asalzburger commented on Fatras/include/ActsFatras/Digitization/Channelizer.hpp
> +    // Go from 2D-path to 3D-path by applying thickness
I don't see where the thickness is applied here.

2023-11-10 08:14 UTC, asalzburger commented on Fatras/include/ActsFatras/Digitization/Channelizer.hpp
> +    for (auto& seg : segments) {
Forget the comment above, it's clear now.

2023-11-10 08:14 UTC, asalzburger commented on Fatras/include/ActsFatras/Digitization/Channelizer.hpp
> +      seg.activation = std::hypot(segThickness, seg.activation);
Is there a unit test for this?
I.e. that the 3D path length from the segments add up to the full 3D path after segmentation?

2023-11-10 08:14 UTC, asalzburger commented on Tests/UnitTests/Fatras/Digitization/ChannelizerTests.cpp
> +  BOOST_CHECK_CLOSE(segments[0].activation, helper.thickness, 1.e-8);
This is right through, I see.

2023-11-10 08:14 UTC, asalzburger commented on Tests/UnitTests/Fatras/Digitization/ChannelizerTests.cpp
> +  BOOST_CHECK_CLOSE(segments[0].activation, std::hypot(disp, helper.thickness),
Next check: done. Tiltet through in one step.

2023-11-12 14:21 UTC, benjaminhuth commented
@asalzburger The PR should now be ready, can you approve?

2023-11-12 20:15 UTC, AJPfleger requested changes

2023-11-12 20:15 UTC, AJPfleger commented on Tests/UnitTests/Fatras/Digitization/SegmentizerTests.cpp
> +  BOOST_CHECK(sSegment.size() == 2);
```suggestion
  BOOST_CHECK_EQUAL(nSegments.size(), 1);
  BOOST_CHECK_EQUAL(nSegments[0].bin[0], 0);
  BOOST_CHECK_EQUAL(nSegments[0].bin[1], 161);

  // Test: now opver more phi strips
  Acts::Vector2 sPositionS(6.76, 0.5);
  Acts::Vector2 sPositionE(7.03, -0.3);
  auto sSegment =
      cl.segments(geoCtx, *radialDisc, strips, {sPositionS, sPositionE});
  BOOST_CHECK_EQUAL(sSegment.size(), 59);

  // Test: jump over R boundary, but stay in phi bin
  sPositionS = Acts::Vector2(6.76, 0.);
  sPositionE = Acts::Vector2(7.83, 0.);
  sSegment = cl.segments(geoCtx, *radialDisc, strips, {sPositionS, sPositionE});
  BOOST_CHECK_EQUAL(sSegment.size(), 2);
```

2023-11-13 10:34 UTC, asalzburger approved these changes

2023-11-13 12:56 UTC, merged

2023-11-13 13:25 UTC, acts-project-service commented
## :red_circle: Athena integration test results [a01f82a854d0ce09ed29d739185d3044788dc50a]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/33897580) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6472121)!