refactor: Make seeding config more understandable
acts-project/acts pull request #2652
Opened 2023-11-13 10:41 UTC by LuisFelipeCoelho

2023-11-13 13:48 UTC, paulgessinger commented on Core/include/Acts/Seeding/SeedFinderOrthogonalConfig.hpp
If these become doxygen comments, we could pull most or all of this into the main documentation.

2023-11-13 13:59 UTC, LuisFelipeCoelho commented on Core/include/Acts/Seeding/SeedFinderConfig.hpp
reordering + adding and changing comments. But no configuration is renamed or removed

2023-11-13 13:59 UTC, LuisFelipeCoelho commented on Core/include/Acts/Seeding/SeedConfirmationRangeConfig.hpp
Sure I will do that

2023-11-13 14:07 UTC, AJPfleger requested changes

2023-11-13 14:07 UTC, AJPfleger commented on Core/include/Acts/Seeding/SeedFinderConfig.hpp
> +  float cotThetaMax = 10.01788;  // equivalent to 3 eta (pseudorapidity)
```suggestion
  float cotThetaMax = 10.01788;  // equivalent to eta = 3 (pseudorapidity)
```
(Only if possible without linebreak)

2023-11-13 14:07 UTC, AJPfleger commented on Core/include/Acts/Seeding/SeedFinderConfig.hpp
> +  // Term that accounts for the thickness of scattering medium in radiation lengths in the Lynch \& Dahl correction to the Highland equation
```suggestion
  // Term that accounts for the thickness of scattering medium in radiation lengths in the Lynch & Dahl correction to the Highland equation
```

2023-11-13 14:07 UTC, AJPfleger commented on Core/include/Acts/Seeding/SeedFinderOrthogonalConfig.hpp
> +  // Term that accounts for the thickness of scattering medium in radiation lengths in the Lynch \& Dahl correction to the Highland equation
```suggestion
  // Term that accounts for the thickness of scattering medium in radiation lengths in the Lynch & Dahl correction to the Highland equation
```

2023-11-13 14:28 UTC, LuisFelipeCoelho commented on Core/include/Acts/Seeding/SeedFinderConfig.hpp
> +  // Term that accounts for the thickness of scattering medium in radiation lengths in the Lynch \& Dahl correction to the Highland equation
Thanks for the fixes @AJPfleger

2023-11-13 14:48 UTC, paulgessinger commented
Do we have an idea why the physmon output changes?

2023-11-13 15:59 UTC, LuisFelipeCoelho commented
> Do we have an idea why the physmon output changes?

Maybe some default values of the orthogonal seeding were different from the default, I will check if that is the case

2023-11-29 10:19 UTC, LuisFelipeCoelho commented
FYI: @CarloVarni

2023-11-29 10:51 UTC, AJPfleger requested changes

2023-11-29 10:51 UTC, AJPfleger commented on Core/include/Acts/Seeding/SeedConfirmationRangeConfig.hpp
> +  /// Minimum radius for inner seed component required in quality in seed
```suggestion
  /// Minimum radius for inner seed component required in quality seed
```

2023-11-29 17:26 UTC, AJPfleger approved these changes

2023-12-04 18:58 UTC, acts-project-service commented
## :red_circle: Athena integration test results [c561d529ea1ac3cd660b5cf7f505f69b8b628ddb]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/34464351) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6572094)!

2023-12-04 19:35 UTC, paulgessinger requested changes
~~This seems to fail the Athena build. Can you either make it so it's backward compatible @LuisFelipeCoelho or we need to hold this until v32 next week. ~~

Build failure is likely because the branch is not even with main. I'll update and retrigger

2023-12-05 06:52 UTC, paulgessinger commented
Ok it's green now, so good to go.

2023-12-05 06:53 UTC, paulgessinger approved these changes

2023-12-05 21:17 UTC, paulgessinger approved these changes

2023-12-06 00:59 UTC, merged