refactor: name change of FTF -> GBTS seeding
acts-project/acts pull request #2853
Opened 2023-12-21 17:56 UTC by Rosie-Hasan

Change naming of new seeding algorithm from FTF (FastTrackFinder) to GBTS (Graph Based Track Seeding) as this is a clearer desription of the algorithm. Name changes disccuessed in issue #2831 .  
Code implemented in PRs #2227  #2726  and more details given presented at [ACTS-ITK presention ](https://indico.cern.ch/event/1321208/#20-update-on-ftf-implementatio).

2024-01-08 07:43 UTC, AJPfleger requested changes
Looks already quite fine. I think, there are only(?) 3 things to change:
- Start variable names with lower case
- Drop most of the underscores except for `m_afterThatNoUnderScores` and maybe in the python scripts
- Change `*ipp` to `.*cpp` when you are already renaming files. But this is argueable.

2024-01-08 07:43 UTC, AJPfleger commented on Core/include/Acts/Seeding/GbtsTrackingFilter.hpp
> +
I think, this not part of this PR.

2024-01-08 07:43 UTC, AJPfleger commented on Core/include/Acts/Seeding/GbtsTrackingFilter.hpp
> +    // std::endl ; chi2 test
This as well.

2024-01-08 07:43 UTC, AJPfleger commented on Core/include/Acts/Seeding/SeedFinderGbts.hpp
> +                 const GbtsGeometry<external_spacepoint_t> &Gbtsgeo);
```suggestion
  SeedFinderGbts(const SeedFinderGbtsConfig<external_spacepoint_t> &config,
                 const GbtsGeometry<external_spacepoint_t> &gbtsGeo);
```

For variable names we should start with lower case. (Also some occurrences below)

2024-01-08 07:43 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/GbtsSeedingAlgorithm.hpp
> +  std::map<std::pair<int, int>, std::pair<int, int>> Make_ACTS_Gbts_Map() const;
```suggestion
  std::map<std::pair<int, int>, std::pair<int, int>> makeActsGbtsMap() const;
```
Similar below.

2024-01-08 07:43 UTC, AJPfleger commented on Core/include/Acts/Seeding/SeedFinderGbts.ipp
> +        vSP.push_back(&(*sIt)->m_n1->m_sp_Gbts);
```suggestion
        vSP.push_back(&(*sIt)->m_n1->m_spGbts);
```

2024-01-09 12:01 UTC, Rosie-Hasan commented
@AJPfleger Thank you for your help, I am making the name changes for the variables. For the ipp -> cpp I just wanted to double check as all the other files in core seeding are ipp/hpp

2024-01-09 12:34 UTC, AJPfleger commented
> For the ipp -> cpp I just wanted to double check as all the other files in core seeding are ipp/hpp
I see, good spot. Then let's keep them as they are :)

2024-01-09 13:19 UTC, AJPfleger requested changes
I think after these changes we are ready to go.

There are still a few other variables that need to be renamed, but they are not really in the scope of this PR. Since you planned to refactor/modernise the code code, some of them might even vanish. So no need to put too much thinking into it right now.

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/GbtsSeedingAlgorithm.hpp
> +    std::map<std::pair<int, int>, std::pair<int, int>> ACTSGbtsMap;
```suggestion
    std::map<std::pair<int, int>, std::pair<int, int>> ActsGbtsMap;
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/include/ActsExamples/TrackFinding/GbtsSeedingAlgorithm.hpp
> +  std::map<std::pair<int, int>, std::pair<int, int>> makeACTSGbtsMap() const;
```suggestion
  std::map<std::pair<int, int>, std::pair<int, int>> makeActsGbtsMap() const;
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/src/GbtsSeedingAlgorithm.cpp
> +  mGbtsgeo = std::make_unique<Acts::GbtsGeometry<SimSpacePoint>>(
```suggestion
  m_gbtsGeo = std::make_unique<Acts::GbtsGeometry<SimSpacePoint>>(
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/src/GbtsSeedingAlgorithm.cpp
> +  Acts::SeedFinderGbts<SimSpacePoint> finder(m_cfg.seedFinderConfig, *mGbtsgeo);
```suggestion
  Acts::SeedFinderGbts<SimSpacePoint> finder(m_cfg.seedFinderConfig, *m_gbtsGeo);
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/src/GbtsSeedingAlgorithm.cpp
> +  SimSeedContainer seeds = finder.createSeeds(internalRoi, *mGbtsgeo);
```suggestion
  SimSeedContainer seeds = finder.createSeeds(internalRoi, *m_gbtsGeo);
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/src/GbtsSeedingAlgorithm.cpp
> +  m_cfg.ACTSGbtsMap = makeACTSGbtsMap();
```suggestion
  m_cfg.ActsGbtsMap = makeActsGbtsMap();
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/src/GbtsSeedingAlgorithm.cpp
> +  GbtsSpacePoints.reserve(
```suggestion
  std::vector<Acts::GbtsSP<ActsExamples::SimSpacePoint>> gbtsSpacePoints;
  gbtsSpacePoints.reserve(
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/src/GbtsSeedingAlgorithm.cpp
> +  return GbtsSpacePoints;
```suggestion
  return gbtsSpacePoints;
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/src/GbtsSeedingAlgorithm.cpp
> +        m_cfg.ACTSGbtsMap
```suggestion
        m_cfg.ActsGbtsMap
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Python/src/TrackFinding.cpp
> +      trackingGeometry, ACTSGbtsMap, fill_module_csv, inputClusters);
```suggestion
      trackingGeometry, ActsGbtsMap, fill_module_csv, inputClusters);
```

2024-01-09 13:19 UTC, AJPfleger commented on Examples/Algorithms/TrackFinding/src/GbtsSeedingAlgorithm.cpp
> +      GbtsSpacePoints.emplace_back(&spacePoint, Gbts_id, combined_id);
```suggestion
      gbtsSpacePoints.emplace_back(&spacePoint, Gbts_id, combined_id);
```

2024-01-09 15:20 UTC, AJPfleger approved these changes

2024-01-09 15:26 UTC, merged

2024-01-09 15:30 UTC, acts-project-service commented
## :red_circle: Athena integration test results [53bcd7462d688f7db6ef2fa47301a6ed1b681d5d]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/35130095) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/6708874)!