refactor!: Deduplicate `estimateTrackParamsFromSeed` code
acts-project/acts pull request #3866
Opened 2024-11-15 16:07 UTC by andiwand

After a couple of iterations we can deduplicate the code with the free param estimation

blocked by
- https://github.com/acts-project/acts/pull/3835
- https://github.com/acts-project/acts/pull/3832
- https://github.com/acts-project/acts/pull/3863

2024-11-20 15:02 UTC, benjaminhuth requested changes

2024-11-20 15:02 UTC, benjaminhuth commented on Core/include/Acts/Seeding/EstimateTrackParamsFromSeed.hpp
> +BoundVector estimateTrackParamsFromSeed(const GeometryContext& gctx,
`Acts::Result` would be nice

2024-11-20 15:02 UTC, benjaminhuth commented on Core/include/Acts/Seeding/EstimateTrackParamsFromSeed.hpp
> +  auto lpResult = surface.globalToLocal(gctx, origin, direction);
directly return result here

2024-11-20 15:38 UTC, benjaminhuth submitted a review, later dismissed
Looks good!

2024-11-21 14:43 UTC, benjaminhuth approved these changes

2024-11-22 07:31 UTC, merged

2024-11-22 08:23 UTC, acts-project-service commented
## :red_circle: Athena integration test results [5c3a8b81117927452c50c0947d2b47e6f76c1721]
### Build job with this PR failed!
Please investigate the [build job](https://gitlab.cern.ch/acts/acts-athena-ci/-/jobs/46351355) for the [pipeline](https://gitlab.cern.ch/acts/acts-athena-ci/-/pipelines/8567819)!

2024-11-23 17:36 UTC, paulgessinger commented
So looks like this changes specifically the HGTD workflow counts in Athena.