Remove units namespace
acts-project/acts pull request #433
Opened 2020-09-03 12:40 UTC by FabianKlimpel

This PR removes the `units` namespace and replaces the currently used variables of this namespace by `UnitConstants`.

2020-09-03 15:38 UTC, msmk0 requested changes
Looks good. I think you have some changes from #425 mixed into this PR. Please remove them, then I will merge i.

2020-09-03 15:38 UTC, msmk0 commented on Core/include/Acts/Fitter/KalmanFitter.hpp
> +
This one neither.

2020-09-03 15:38 UTC, msmk0 commented on Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp
> +
Should not be part of this PR.

2020-09-04 05:35 UTC, FabianKlimpel commented on Core/include/Acts/Fitter/KalmanFitter.hpp
> +
Gone

2020-09-04 05:35 UTC, FabianKlimpel commented on Core/include/Acts/TrackFinder/CombinatorialKalmanFilter.hpp
> +
Gone

2020-09-04 05:36 UTC, FabianKlimpel commented on Core/include/Acts/Fitter/KalmanFitter.hpp
> +
Gone

2020-09-04 05:37 UTC, FabianKlimpel commented on Core/include/Acts/Propagator/Navigator.hpp
> +        double mom = stepper.momentum(state.stepping) / UnitConstants::GeV;
Well, I don't know the intention of the snippet and since it is not used, I keep it as it is

2020-09-04 06:27 UTC, msmk0 commented on Core/include/Acts/Propagator/Navigator.hpp
> +        double mom = stepper.momentum(state.stepping) / UnitConstants::GeV;
Fair enough.

2020-09-04 06:28 UTC, msmk0 approved these changes

2020-09-04 08:03 UTC, msmk0 approved these changes

2020-09-04 08:05 UTC, merged