Fix vertexing examples & update vertexing tutorial docs
acts-project/acts pull request #716
Opened 2021-02-16 11:12 UTC by baschlag

1. This PR fixes the vertexing examples issues we were seeing: primary vertexing specific track selection cuts that are needed for the fitters/finders to converge are added back (apparently they have been removed in some Examples rework in the past).
2. Also the vertexing tutorial docs were not up to date anymore with the ```TutorialVertexFinderAlgorithm``` in the Examples and are updated in this PR.

2021-02-17 08:55 UTC, asalzburger requested changes
In general this is fine, I was just wondering if we could have three parameters that are configurable with the ActsExample::Options ?

2021-02-17 08:55 UTC, asalzburger commented on Examples/Run/Vertexing/Pythia8/AdaptiveMultiVertexFinderExample.cpp
> +  selectParticles.ptMin = 500_MeV;
Can we configure those with options?

2021-02-17 08:55 UTC, asalzburger commented on Examples/Run/Vertexing/Pythia8/IterativeVertexFinderExample.cpp
> +  selectParticles.ptMin = 500_MeV;
Same here ...

2021-02-17 08:55 UTC, asalzburger commented on Examples/Run/Vertexing/Pythia8/TutorialVertexFinderExample.cpp
> +  selectParticles.ptMin = 500_MeV;
Once again ...

2021-02-17 08:55 UTC, asalzburger commented on Examples/Run/Vertexing/Pythia8/VertexFitterExample.cpp
> +  selectParticles.ptMin = 500_MeV;
I keep repeating myself :-P

2021-02-17 08:55 UTC, asalzburger commented on Examples/Run/Vertexing/VertexFinderReaderExample.cpp
> +  selectParticles.ptMin = 500_MeV;
ok ...

2021-02-17 10:44 UTC, baschlag commented on Examples/Run/Vertexing/Pythia8/AdaptiveMultiVertexFinderExample.cpp
> +  selectParticles.ptMin = 500_MeV;
Done.

2021-02-17 10:44 UTC, baschlag commented on Examples/Run/Vertexing/Pythia8/IterativeVertexFinderExample.cpp
> +  selectParticles.ptMin = 500_MeV;
Done.

2021-02-17 10:44 UTC, baschlag commented on Examples/Run/Vertexing/Pythia8/TutorialVertexFinderExample.cpp
> +  selectParticles.ptMin = 500_MeV;
Once again done :)

2021-02-17 10:45 UTC, baschlag commented on Examples/Run/Vertexing/Pythia8/VertexFitterExample.cpp
> +  selectParticles.ptMin = 500_MeV;
Haha :-) they are all configurable now

2021-02-17 10:46 UTC, baschlag commented
> In general this is fine, I was just wondering if we could have three parameters that are configurable with the ActsExample::Options ?

Good point, thanks. I've made these parameters configurable now.

2021-02-17 11:05 UTC, asalzburger requested changes
Almost, I see where you are coming from, but in all other Algorithm packages, we have one File such as e.g. `VertexingOptions` that then has the different `addIterativeFinderOptions(...)` etc. 

For keeping a homogeneous repo I think we should try to use the same approach everywhere.

2021-02-17 11:22 UTC, baschlag commented
> Almost, I see where you are coming from, but in all other Algorithm packages, we have one File such as e.g. `VertexingOptions` that then has the different `addIterativeFinderOptions(...)` etc.
> 
> For keeping a homogeneous repo I think we should try to use the same approach everywhere.

Oh I missed that. Yes, that's a lot cleaner and avoids duplications. Perfect. Will change it.

2021-02-17 12:41 UTC, baschlag commented
> Almost, I see where you are coming from, but in all other Algorithm packages, we have one File such as e.g. `VertexingOptions` that then has the different `addIterativeFinderOptions(...)` etc.
> 
> For keeping a homogeneous repo I think we should try to use the same approach everywhere.

Done. Please check.

2021-02-17 12:57 UTC, asalzburger approved these changes
Excellent.

2021-02-17 15:55 UTC, merged

2021-02-23 13:09 UTC, ZhangGang00 commented
Hi @baschlag ,

You required "vertexing-eta-max" and "vertexing-pt-min" to restrict the tracks in the barrel just for better track reconstruction. It does not mean ACTS AMVF cannot deal with tracks almost along Z axis, right? For FASER, our tracks are almost along Z axis. Is it OK for ACTS AMVF?

Cheers,
Gang